name: islamic_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: any



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/files/
    - assets/images/

  fonts:
    - family: "El Messiri"
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
        - asset: assets/fonts/ElMessiri-Medium.ttf
        - asset: assets/fonts/ElMessiri-Regular.ttf
flutter_intl:
  enabled: true
